### ISSUE TITLE
cmonkey2 does not work with meme 4.11

### ISSUE THREAD

**Issue by NelleV** [baliga-lab/cmonkey2#51]
Hello,

Just a brief comment that cmonkey2 does not work with meme 4.11.

Thanks for the great work,
Nelle

**Comment by weiju** [comment]
Hi, thank you very much for the feedback ! There seems to have been some changes in the MEME/MAST data format/parameterization between the 4.10.x to 4.11.x versions. I will add support for the 4.11.x versions soon.

**Comment by weiju** [comment]
MEME 4.11.x has made the following changes that broke the integration with cmonkey2:

  - structure of the MAST output file is different, motif numbers are now defined globally
  - Tomtom has renamed/removed the pseudo and threshold switches

We added logic to handle those special cases in order to support the MEME 4.11.x tools.
