### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by prashantkum7** [baliga-lab/cmonkey2#66]
Hi,

When I run cMonkey, it reaches to the stage with line 244 in util.py file, nut then
gives the following error.

File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Could you please help me with this?

Thanks,
Prashant

**Comment by weiju** [comment]
Hi, without knowing more details about your run I am assuming you are likely using an organism that is now not available on RSAT anymore. Unfortunately, it seems that a number of organisms have been removed from RSAT's downloadable databases, which includes among others the example organism Halobacterium (code "hal"). Our RSAT module is assuming the existence of a certain folder structure within RSAT and the recent changes lead to this error since the documents simply don't exist on those servers anymore.
Are you perhaps using something like hal ?

**Comment by prashantkum7** [comment]
Hi,

I am using Ecoli. I have managed to run with '--nomotifs' option. But it doesn;t work if 
I don't use this option. It is the same error which cfbuenabadn got.

**Comment by weiju** [comment]
Thanks for the information, I will have a look into this

**Comment by weiju** [comment]
I am using this on 2 different configurations and it runs without problems here with MEME 4.9.1 and 4.10.2. Please note that support MEME 4.11.x and higher is currently still under development and is not available in the current release.

**Comment by prashantkum7** [comment]
Hi Wei,

Thank you. It works fine with Meme-4.10.2.



Thanks and Regards,
Prashant Kumar | PhD student, Chemical Engineering
University of Wisconsin Madison, USA
+1-608 770 0539

**Comment by prashantkum7** [comment]
Hi,

Could you please tell the average time cmonkey takes for a bacterial cell (approx. 5000 genes).

Thanks

**Comment by weiju** [comment]
Hi,
the time depends greatly on the number of iterations + clusters and your hardware.
A run with 2000 iterations and 40 clusters takes 1-2 hours on a 4 core i7 2.2 GHz
Linux machine, 8 GB and local hard disk. Typical E.coli runs can take overnight.

**Comment by weiju** [comment]
Related to issue #51
